# Generated by Django 5.0.3 on 2024-03-13 15:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1_icon', models.CharField(blank=True, max_length=500, null=True)),
                ('box1_title', models.CharField(blank=True, max_length=250, null=True)),
                ('box1_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('box2_icon', models.CharField(blank=True, max_length=500, null=True)),
                ('box2_title', models.CharField(blank=True, max_length=250, null=True)),
                ('box2_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('box3_icon', models.CharField(blank=True, max_length=500, null=True)),
                ('box3_title', models.CharField(blank=True, max_length=250, null=True)),
                ('box3_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('map_iframe', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribe_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
