# Generated by Django 5.0 on 2024-06-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='twilio_from_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='twilio_message_service_sid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='facebook',
            field=models.CharField(blank=True, default='https://facebook.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_col1_button',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_col1_button_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_col1_subtitle',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_col1_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_col2_title1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_col2_title2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_copyright',
            field=models.CharField(max_length=500, default='Synclo LLC', null=True)
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='instagram',
            field=models.CharField(blank=True, default='https://instagram.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='linkedin',
            field=models.CharField(blank=True, default='https://linkedin.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='pinterest',
            field=models.CharField(blank=True, default='https://pinterest.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='twitter',
            field=models.CharField(blank=True, default='https://twitter.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='youtube',
            field=models.CharField(blank=True, default='https://youtube.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='ssl_commerze_store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='ssl_commerze_store_pass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='tag_line',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='email_address',
            field=models.TextField(blank=True, default='admin@synclo.io', null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='name',
            field=models.TextField(default='Synclo'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='openai_api',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
