from django.contrib import admin
from hrm.models import *

admin.site.register(Notification)
admin.site.register(Branch)
admin.site.register(Department)
admin.site.register(Designation)
admin.site.register(LeaveType)
admin.site.register(Leave)
admin.site.register(Payroll)
admin.site.register(BasicSalary)
admin.site.register(Payslip)
admin.site.register(Allowance)
admin.site.register(Deduction)
admin.site.register(TerminationType)
admin.site.register(Termination)
admin.site.register(warning)
admin.site.register(JobType)
admin.site.register(Meeting)
admin.site.register(Notice)
admin.site.register(Holiday)
admin.site.register(Event)