# Generated by Django 5.0.3 on 2024-03-13 15:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField()),
                ('button_text', models.CharField(max_length=200)),
                ('button_url', models.CharField(max_length=1000)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_badge_title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pricingPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
